## Problema de Alocação de Motoristas

**Problema de Alocação de Motoristas -** Devido ao número inconstante de passageiros, uma companhia de ônibus necessita de um número variado de motoristas dependendo do horário considerado. O número mínimo de motoristas necessários para cada período é apresentados na tabela abaixo.

                  1 às 5      5 às 9    9 às 13       13 às 17      17 às 21     21 à 1	

    Motoristas:     15         30         26             32           30          19
              
Os motoristas trabalham 8 horas seguidas, podendo começar 1, 5, 9, 13, 17 ou 21 horas. Formule o problema obtendo um modelo matemático que possibilite, a companhia em questão, reduzir o número de motoristas.

x1 = Quantidade de motoristas que têm horário de início às 1 hora

x2 = Quantidade de motoristas que têm horário de início às 5 horas

x3 = Quantidade de motoristas que têm horário de início às 9 horas

x4 = Quantidade de motoristas que têm horário de início às 13 horas

x5 = Quantidade de motoristas que têm horário de início às 17 horas

x6 = Quantidade de motoristas que têm horário de início às 21 horas

MIN x1 + x2 + x3 + x4 + x5 + x6

sujeito a:

x6 + x1 >= 15

x1 + x2 >= 30

x2 + x3 >= 26

x3 + x4 >= 32

x4 + x5 >= 30

x5 + x6 >= 19

x1, x2, x3, x4, x5, x6 >= 0

x1, x2, x3, x4, x5, x6 ∈ Z

In [1]:
from docplex.mp.model import Model
import cplex

m = Model(name='Fabrica_De_Moveis')
x_1 = m.integer_var(name='x_1')
x_2 = m.integer_var(name='x_2')
x_3 = m.integer_var(name='x_3')
x_4 = m.integer_var(name='x_4')
x_5 = m.integer_var(name='x_5')
x_6 = m.integer_var(name='x_6')

m.add_constraint(x_6 + x_1 >= 15)
m.add_constraint(x_1 + x_2 >= 30)
m.add_constraint(x_2 + x_3 >= 26)
m.add_constraint(x_3 + x_4 >= 32)
m.add_constraint(x_4 + x_5 >= 30)
m.add_constraint(x_5 + x_6 >= 19)

m.add_constraint(x_1 >= 0)
m.add_constraint(x_2 >= 0)
m.add_constraint(x_3 >= 0)
m.add_constraint(x_4 >= 0)
m.add_constraint(x_5 >= 0)
m.add_constraint(x_6 >= 0)

m.minimize(x_1 + x_2 + x_3 + x_4 + x_5 + x_6)
m.solve()
print(m.solution)

solution for: Fabrica_De_Moveis
objective: 81
x_1=25
x_2=5
x_3=21
x_4=11
x_5=19



### Usando o método de força bruta

1) testar, para cada combinação de m colunas de A, se elas formam uma base; 

2) calcular, para cada base, a solução básica associada a ela; 

3) calcular, para todas as SBV obtidas, o valor da função objetivo.

MIN x1 + x2 + x3 + x4 + x5 + x6

sujeito a:

x6 + x1 - x7 = 15

x1 + x2 - x8 = 30

x2 + x3 - x9 = 26

x3 + x4 - x10 = 32

x4 + x5 - x11 = 30

x5 + x6 - x12 = 19

x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12 >= 0

In [2]:
from math import factorial
from __future__ import print_function
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
A = np.array([[1, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0],
              [1, 1, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0],
              [0, 1, 1, 0, 0, 0, 0, 0, -1, 0, 0, 0],
              [0, 0, 1, 1, 0, 0, 0, 0, 0, -1, 0, 0],
              [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, -1, 0],
              [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, -1]])

In [4]:
b = np.array([[15], 
              [30],
              [26],
              [32],
              [30],
              [19]])

In [5]:
c = np.array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0])

In [6]:
m = len(A)
print('m:', m)

n = len(A[0])
print('n:', n)

combinacoes = factorial(n)/(factorial(m)*(factorial(n-m)))

print('O número máximo de soluções básicas:', combinacoes)

m: 6
n: 12
O número máximo de soluções básicas: 924.0


In [7]:
def verifica_solucao_viavel(x):
    '''
        Função que verifica se a solução é viável
        
        >>> verifica_solucao_viavel([0, 0, [125.], 0, [125.], [475.], 0])
            Esta é uma solução básica viável
            True
        >> verifica_solucao_viavel([0, 0, 0, [300.], [-950.], 0, [500.]])
            Esta NÃO é uma solução básica viável
            False
        >> verifica_solucao_viavel([1, 0, 1, 0, 1, 0, 0])
            Esta é uma solução básica viável
            True
    '''
    
    xB_bool = []

    for w in range(0, len(x)):
        if(x[w] >= 0):
            xB_bool.append(True)           
        else:
            xB_bool.append(False)

        try:
            if(x[w][0] >= 0):
                xB_bool.append(True)
            else:
                xB_bool.append(False)
        except:
            pass
            
    if(all(xB_bool)):
        print('Esta é uma solução básica viável')
        return True
    else:
        print('Esta NÃO é uma solução básica viável')
        return False

In [8]:
solucoes_viaveis = np.array([[0,0,0,0,0,0], 0,0,0])
todas_solucoes = np.array([[0,0,0,0,0,0], 0,0,0])
cont_x = 0

for w in range(0, n):
    for y in range(w+1, n):
        for z in range(y+1, n):
            for j in range(z+1, n):
                for k in range(j+1, n):
                    for l in range(k+1, n):
            
                        # Id da solução
                        cont_x = cont_x + 1;
                        print('\nx', cont_x)

                        # Conjunto de índices IB
                        IB = [w,y,z,j,k,l]
                        print('IB =', IB[0]+1, IB[1]+1, IB[2]+1, IB[3]+1, IB[4]+1, IB[5]+1)

                        # B
                        B = np.array([A[0][w], A[0][y], A[0][z], A[0][j], A[0][k], A[0][l]])
                        for v in range (1, m):
                            B = np.row_stack(tup=(B, [A[v][w], A[v][y], A[v][z], A[v][j], A[v][k], A[v][l]]))
                        print('B =', B, '\n')

                        # Verificando se B é uma base
                        v, V =  np.linalg.eig(B)
                        if(v.all() == 0):
                            print('A matriz B não é uma base')
                            print('A linha LD é:')
                            print (B[v == 0,:])
                            print('\n---------------------------------------------------------------------------\n')

                            # Colocar na tabela de soluções básicas, com informações vazias
                            todas_solucoes = np.row_stack((todas_solucoes, [[IB[0]+1, IB[1]+1, IB[2]+1, IB[3]+1, IB[4]+1, IB[5]+1], cont_x, [], []]))
                            continue

                        # B-1
                        try:
                            B1 = np.linalg.inv(B)
                            print('B-1 =', B1, '\n')
                        except:
                            print("B-1 não existe")
                            todas_solucoes = np.row_stack((todas_solucoes, [[IB[0]+1, IB[1]+1, IB[2]+1, IB[3]+1, IB[4]+1, IB[5]+1], cont_x, [], []]))
                            print('\n---------------------------------------------------------------------------\n')
                            continue

                        # xB
                        xB = B1.dot(b)
                        print('xB =', xB, '\n')

                        # x
                        x = []
                        for v in range (0, n):              
                            if(v == IB[0]):
                                x.append(np.round(xB[0], 3))
                            elif(v == IB[1]):
                                x.append(np.round(xB[1], 3))
                            elif(v == IB[2]):
                                x.append(np.round(xB[2], 3))
                            elif(v == IB[3]):
                                x.append(np.round(xB[3], 3))
                            elif(v == IB[4]):
                                x.append(np.round(xB[4], 3))
                            elif(v == IB[5]):
                                x.append(np.round(xB[5], 3))
                            else:
                                x.append(0)
                        print('x =', x, '\n')

                        # cTx
                        cTx = np.transpose(c).dot(x)
                        print('cTx =', cTx, '\n')

                        # Colocar na tabela de soluções básicas
                        todas_solucoes = np.row_stack((todas_solucoes, [[IB[0]+1, IB[1]+1, IB[2]+1, IB[3]+1, IB[4]+1, IB[5]+1], cont_x, cTx, x]))

                        # Se a solução for viável, colocar na tabela de soluções viáveis
                        if(verifica_solucao_viavel(x) == True):
                            solucoes_viaveis = np.row_stack((solucoes_viaveis, [[IB[0]+1, IB[1]+1, IB[2]+1, IB[3]+1, IB[4]+1, IB[5]+1], cont_x, cTx, x]))

                        print('\n---------------------------------------------------------------------------\n')


<ipython-input-8-7772126bda9c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  solucoes_viaveis = np.array([[0,0,0,0,0,0], 0,0,0])
<ipython-input-8-7772126bda9c>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  todas_solucoes = np.array([[0,0,0,0,0,0], 0,0,0])
/home/myllah/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must


x 1
IB = 1 2 3 4 5 6
B = [[1 0 0 0 0 1]
 [1 1 0 0 0 0]
 [0 1 1 0 0 0]
 [0 0 1 1 0 0]
 [0 0 0 1 1 0]
 [0 0 0 0 1 1]] 

B-1 não existe

---------------------------------------------------------------------------


x 2
IB = 1 2 3 4 5 7
B = [[ 1  0  0  0  0 -1]
 [ 1  1  0  0  0  0]
 [ 0  1  1  0  0  0]
 [ 0  0  1  1  0  0]
 [ 0  0  0  1  1  0]
 [ 0  0  0  0  1  0]] 

B-1 = [[ 0.  1. -1.  1. -1.  1.]
 [ 0.  0.  1. -1.  1. -1.]
 [ 0.  0.  0.  1. -1.  1.]
 [ 0.  0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  0.  1.]
 [-1.  1. -1.  1. -1.  1.]] 

xB = [[25.]
 [ 5.]
 [21.]
 [11.]
 [19.]
 [10.]] 

x = [array([25.]), array([5.]), array([21.]), array([11.]), array([19.]), 0, array([10.]), 0, 0, 0, 0, 0] 

cTx = [81.] 

Esta é uma solução básica viável

---------------------------------------------------------------------------


x 3
IB = 1 2 3 4 5 8
B = [[ 1  0  0  0  0  0]
 [ 1  1  0  0  0 -1]
 [ 0  1  1  0  0  0]
 [ 0  0  1  1  0  0]
 [ 0  0  0  1  1  0]
 [ 0  0  0  0  1  0]] 

B-1 = [[ 1.  0.  0.  0. 


x 50
IB = 1 2 3 6 7 8
B = [[ 1  0  0  1 -1  0]
 [ 1  1  0  0  0 -1]
 [ 0  1  1  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  1  0  0]] 

A matriz B não é uma base
A linha LD é:
[[0 0 0 1 0 0]]

---------------------------------------------------------------------------


x 51
IB = 1 2 3 6 7 9
B = [[ 1  0  0  1 -1  0]
 [ 1  1  0  0  0  0]
 [ 0  1  1  0  0 -1]
 [ 0  0  1  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  1  0  0]] 

A matriz B não é uma base
A linha LD é:
[[0 0 0 1 0 0]]

---------------------------------------------------------------------------


x 52
IB = 1 2 3 6 7 10
B = [[ 1  0  0  1 -1  0]
 [ 1  1  0  0  0  0]
 [ 0  1  1  0  0  0]
 [ 0  0  1  0  0 -1]
 [ 0  0  0  0  0  0]
 [ 0  0  0  1  0  0]] 

A matriz B não é uma base
A linha LD é:
[[0 0 0 1 0 0]]

---------------------------------------------------------------------------


x 53
IB = 1 2 3 6 7 11
B = [[ 1  0  0  1 -1  0]
 [ 1  1  0  0  0  0]
 [ 0  1  1  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  0  0  0 

 [-0. -0. -0. -1.  1. -1.]] 

xB = [[ 15.]
 [ 15.]
 [ 11.]
 [ 19.]
 [-11.]
 [-21.]] 

x = [array([15.]), array([15.]), 0, array([11.]), array([19.]), 0, 0, 0, array([-11.]), array([-21.]), 0, 0] 

cTx = [60.] 

Esta NÃO é uma solução básica viável

---------------------------------------------------------------------------


x 101
IB = 1 2 4 5 9 11
B = [[ 1  0  0  0  0  0]
 [ 1  1  0  0  0  0]
 [ 0  1  0  0 -1  0]
 [ 0  0  1  0  0  0]
 [ 0  0  1  1  0 -1]
 [ 0  0  0  1  0  0]] 

B-1 = [[ 1.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.]
 [-1.  1. -1. -0. -0. -0.]
 [ 0.  0.  0.  1. -1.  1.]] 

xB = [[ 15.]
 [ 15.]
 [ 32.]
 [ 19.]
 [-11.]
 [ 21.]] 

x = [array([15.]), array([15.]), 0, array([32.]), array([19.]), 0, 0, 0, array([-11.]), 0, array([21.]), 0] 

cTx = [81.] 

Esta NÃO é uma solução básica viável

---------------------------------------------------------------------------


x 102
IB = 1 2 4 5 9 12
B = [[ 1  0  0  0  0  0]


B = [[ 1  0  0  1  0  0]
 [ 1  1  0  0  0  0]
 [ 0  1  0  0 -1  0]
 [ 0  0  0  0  0  0]
 [ 0  0  1  0  0 -1]
 [ 0  0  1  1  0  0]] 

A matriz B não é uma base
A linha LD é:
[[0 0 1 1 0 0]]

---------------------------------------------------------------------------


x 152
IB = 1 2 5 6 9 12
B = [[ 1  0  0  1  0  0]
 [ 1  1  0  0  0  0]
 [ 0  1  0  0 -1  0]
 [ 0  0  0  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  1  1  0 -1]] 

A matriz B não é uma base
A linha LD é:
[[ 0  0  1  1  0 -1]]

---------------------------------------------------------------------------


x 153
IB = 1 2 5 6 10 11
B = [[ 1  0  0  1  0  0]
 [ 1  1  0  0  0  0]
 [ 0  1  0  0  0  0]
 [ 0  0  0  0 -1  0]
 [ 0  0  1  0  0 -1]
 [ 0  0  1  1  0  0]] 

B-1 = [[ 0.  1. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [-1.  1. -1.  0.  0.  1.]
 [ 1. -1.  1.  0.  0.  0.]
 [-0. -0. -0. -1. -0. -0.]
 [-1.  1. -1.  0. -1.  1.]] 

xB = [[  4.]
 [ 26.]
 [  8.]
 [ 11.]
 [-32.]
 [-22.]] 

x = [array([4.]), array([26.]), 0, 0, array([8.])

IB = 1 2 6 8 10 12
B = [[ 1  0  1  0  0  0]
 [ 1  1  0 -1  0  0]
 [ 0  1  0  0  0  0]
 [ 0  0  0  0 -1  0]
 [ 0  0  0  0  0  0]
 [ 0  0  1  0  0 -1]] 

A matriz B não é uma base
A linha LD é:
[[ 0  0  0  0  0  0]
 [ 0  0  1  0  0 -1]]

---------------------------------------------------------------------------


x 191
IB = 1 2 6 8 11 12
B = [[ 1  0  1  0  0  0]
 [ 1  1  0 -1  0  0]
 [ 0  1  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0 -1  0]
 [ 0  0  1  0  0 -1]] 

A matriz B não é uma base
A linha LD é:
[[ 0  0  0  0 -1  0]]

---------------------------------------------------------------------------


x 192
IB = 1 2 6 9 10 11
B = [[ 1  0  1  0  0  0]
 [ 1  1  0  0  0  0]
 [ 0  1  0 -1  0  0]
 [ 0  0  0  0 -1  0]
 [ 0  0  0  0  0 -1]
 [ 0  0  1  0  0  0]] 

B-1 = [[ 1.  0.  0.  0.  0. -1.]
 [-1.  1.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.]
 [-1.  1. -1.  0.  0.  1.]
 [-0. -0. -0. -1. -0. -0.]
 [-0. -0. -0. -0. -1. -0.]] 

xB = [[ -4.]
 [ 34.]
 [ 19.]
 [  8.]
 [-32.]
 [-30.]] 

x 

 [ 0  0  0  1  0 -1]] 

B-1 = [[ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 1. -1. -0. -0. -0. -0.]
 [ 0.  0.  1. -1.  1.  0.]
 [ 1. -1. -0. -0. -0. -1.]] 

xB = [[ 30.]
 [ 26.]
 [ 30.]
 [-15.]
 [ 24.]
 [-34.]] 

x = [array([30.]), 0, array([26.]), array([30.]), 0, array([-15.]), 0, 0, 0, array([24.]), 0, array([-34.])] 

cTx = [71.] 

Esta NÃO é uma solução básica viável

---------------------------------------------------------------------------


x 246
IB = 1 3 4 6 11 12
B = [[ 1  0  0  1  0  0]
 [ 1  0  0  0  0  0]
 [ 0  1  0  0  0  0]
 [ 0  1  1  0  0  0]
 [ 0  0  1  0 -1  0]
 [ 0  0  0  1  0 -1]] 

B-1 = [[ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0. -1.  1.  0.  0.]
 [ 1. -1. -0. -0. -0. -0.]
 [-0. -0. -1.  1. -1. -0.]
 [ 1. -1. -0. -0. -0. -1.]] 

xB = [[ 30.]
 [ 26.]
 [  6.]
 [-15.]
 [-24.]
 [-34.]] 

x = [array([30.]), 0, array([26.]), array([6.]), 0, array([-15.]), 0, 0, 0, 0, array([-24.]), array([-34.])] 

cTx = [47.] 

B = [[ 1  0  1 -1  0  0]
 [ 1  0  0  0 -1  0]
 [ 0  1  0  0  0 -1]
 [ 0  1  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  1  0  0  0]] 

A matriz B não é uma base
A linha LD é:
[[0 0 1 0 0 0]]

---------------------------------------------------------------------------


x 303
IB = 1 3 6 7 8 10
B = [[ 1  0  1 -1  0  0]
 [ 1  0  0  0 -1  0]
 [ 0  1  0  0  0  0]
 [ 0  1  0  0  0 -1]
 [ 0  0  0  0  0  0]
 [ 0  0  1  0  0  0]] 

A matriz B não é uma base
A linha LD é:
[[0 0 1 0 0 0]]

---------------------------------------------------------------------------


x 304
IB = 1 3 6 7 8 11
B = [[ 1  0  1 -1  0  0]
 [ 1  0  0  0 -1  0]
 [ 0  1  0  0  0  0]
 [ 0  1  0  0  0  0]
 [ 0  0  0  0  0 -1]
 [ 0  0  1  0  0  0]] 

A matriz B não é uma base
A linha LD é:
[[0 0 1 0 0 0]]

---------------------------------------------------------------------------


x 305
IB = 1 3 6 7 8 12
B = [[ 1  0  1 -1  0  0]
 [ 1  0  0  0 -1  0]
 [ 0  1  0  0  0  0]
 [ 0  1  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  1  0  

IB = 1 4 5 8 9 10
B = [[ 1  0  0  0  0  0]
 [ 1  0  0 -1  0  0]
 [ 0  0  0  0 -1  0]
 [ 0  1  0  0  0 -1]
 [ 0  1  1  0  0  0]
 [ 0  0  1  0  0  0]] 

B-1 = [[ 1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  0.  1.]
 [ 1. -1. -0. -0. -0. -0.]
 [-0. -0. -1. -0. -0. -0.]
 [-0. -0. -0. -1.  1. -1.]] 

xB = [[ 15.]
 [ 11.]
 [ 19.]
 [-15.]
 [-26.]
 [-21.]] 

x = [array([15.]), 0, 0, array([11.]), array([19.]), 0, 0, array([-15.]), array([-26.]), array([-21.]), 0, 0] 

cTx = [45.] 

Esta NÃO é uma solução básica viável

---------------------------------------------------------------------------


x 363
IB = 1 4 5 8 9 11
B = [[ 1  0  0  0  0  0]
 [ 1  0  0 -1  0  0]
 [ 0  0  0  0 -1  0]
 [ 0  1  0  0  0  0]
 [ 0  1  1  0  0 -1]
 [ 0  0  1  0  0  0]] 

B-1 = [[ 1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.]
 [ 1. -1. -0. -0. -0. -0.]
 [-0. -0. -1. -0. -0. -0.]
 [ 0.  0.  0.  1. -1.  1.]] 

xB = [[ 15.]
 [ 32.]
 [ 19.]
 [-15.]
 [-26.]
 [ 21.]

 [ 0  1  1  0  0 -1]]

---------------------------------------------------------------------------


x 423
IB = 1 5 6 9 10 11
B = [[ 1  0  1  0  0  0]
 [ 1  0  0  0  0  0]
 [ 0  0  0 -1  0  0]
 [ 0  0  0  0 -1  0]
 [ 0  1  0  0  0 -1]
 [ 0  1  1  0  0  0]] 

B-1 = [[ 0.  1.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  1.]
 [ 1. -1. -0. -0. -0. -0.]
 [-0. -0. -1. -0. -0. -0.]
 [-0. -0. -0. -1. -0. -0.]
 [-1.  1.  0.  0. -1.  1.]] 

xB = [[ 30.]
 [ 34.]
 [-15.]
 [-26.]
 [-32.]
 [  4.]] 

x = [array([30.]), 0, 0, 0, array([34.]), array([-15.]), 0, 0, array([-26.]), array([-32.]), array([4.]), 0] 

cTx = [49.] 

Esta NÃO é uma solução básica viável

---------------------------------------------------------------------------


x 424
IB = 1 5 6 9 10 12
B = [[ 1  0  1  0  0  0]
 [ 1  0  0  0  0  0]
 [ 0  0  0 -1  0  0]
 [ 0  0  0  0 -1  0]
 [ 0  1  0  0  0  0]
 [ 0  1  1  0  0 -1]] 

B-1 = [[ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 1. -1. -0. -0. -0. -0.]
 [-0. -0. -1. -0. -0. -0.]
 

x 481
IB = 2 3 4 5 10 11
B = [[ 0  0  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 1  1  0  0  0  0]
 [ 0  1  1  0 -1  0]
 [ 0  0  1  1  0 -1]
 [ 0  0  0  1  0  0]] 

A matriz B não é uma base
A linha LD é:
[[ 0  1  1  0 -1  0]
 [ 0  0  1  1  0 -1]
 [ 0  0  0  1  0  0]]

---------------------------------------------------------------------------


x 482
IB = 2 3 4 5 10 12
B = [[ 0  0  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 1  1  0  0  0  0]
 [ 0  1  1  0 -1  0]
 [ 0  0  1  1  0  0]
 [ 0  0  0  1  0 -1]] 

A matriz B não é uma base
A linha LD é:
[[ 0  1  1  0 -1  0]
 [ 0  0  1  1  0  0]
 [ 0  0  0  1  0 -1]]

---------------------------------------------------------------------------


x 483
IB = 2 3 4 5 11 12
B = [[ 0  0  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 1  1  0  0  0  0]
 [ 0  1  1  0  0  0]
 [ 0  0  1  1 -1  0]
 [ 0  0  0  1  0 -1]] 

A matriz B não é uma base
A linha LD é:
[[ 1  1  0  0  0  0]
 [ 0  1  1  0  0  0]
 [ 0  0  1  1 -1  0]
 [ 0  0  0  1  0 -1]]

----------------------------------

B = [[ 0  0  0 -1  0  0]
 [ 1  0  0  0  0  0]
 [ 1  1  0  0 -1  0]
 [ 0  1  0  0  0 -1]
 [ 0  0  1  0  0  0]
 [ 0  0  1  0  0  0]] 

B-1 não existe

---------------------------------------------------------------------------


x 539
IB = 2 3 5 7 9 11
B = [[ 0  0  0 -1  0  0]
 [ 1  0  0  0  0  0]
 [ 1  1  0  0 -1  0]
 [ 0  1  0  0  0  0]
 [ 0  0  1  0  0 -1]
 [ 0  0  1  0  0  0]] 

B-1 = [[ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.]
 [-1.  0. -0.  0. -0.  0.]
 [ 0.  1. -1.  1.  0.  0.]
 [ 0.  0.  0.  0. -1.  1.]] 

xB = [[ 30.]
 [ 32.]
 [ 19.]
 [-15.]
 [ 36.]
 [-11.]] 

x = [0, array([30.]), array([32.]), 0, array([19.]), 0, array([-15.]), 0, array([36.]), 0, array([-11.]), 0] 

cTx = [81.] 

Esta NÃO é uma solução básica viável

---------------------------------------------------------------------------


x 540
IB = 2 3 5 7 9 12
B = [[ 0  0  0 -1  0  0]
 [ 1  0  0  0  0  0]
 [ 1  1  0  0 -1  0]
 [ 0  1  0  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  1  0  

B-1 = [[ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [-1.  0.  0.  0.  0.  1.]
 [ 1. -0.  0.  0.  0.  0.]
 [-0.  1. -1. -0. -0. -0.]
 [-1.  0.  0.  1. -1.  1.]] 

xB = [[30.]
 [32.]
 [ 4.]
 [15.]
 [ 4.]
 [ 6.]] 

x = [0, array([30.]), 0, array([32.]), array([4.]), array([15.]), 0, 0, array([4.]), 0, array([6.]), 0] 

cTx = [81.] 

Esta é uma solução básica viável

---------------------------------------------------------------------------


x 600
IB = 2 4 5 6 9 12
B = [[ 0  0  0  1  0  0]
 [ 1  0  0  0  0  0]
 [ 1  0  0  0 -1  0]
 [ 0  1  0  0  0  0]
 [ 0  1  1  0  0  0]
 [ 0  0  1  1  0 -1]] 

B-1 = [[ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  1.  0.]
 [ 1.  0.  0.  0.  0.  0.]
 [-0.  1. -1. -0. -0. -0.]
 [ 1. -0. -0. -1.  1. -1.]] 

xB = [[30.]
 [32.]
 [-2.]
 [15.]
 [ 4.]
 [-6.]] 

x = [0, array([30.]), 0, array([32.]), array([-2.]), array([15.]), 0, 0, array([4.]), 0, 0, array([-6.])] 

cTx = [75.] 

Esta NÃO é uma solução básica viável

---------


x 660
IB = 2 5 6 7 8 10
B = [[ 0  0  1 -1  0  0]
 [ 1  0  0  0 -1  0]
 [ 1  0  0  0  0  0]
 [ 0  0  0  0  0 -1]
 [ 0  1  0  0  0  0]
 [ 0  1  1  0  0  0]] 

B-1 = [[ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. -1.  1.]
 [-1.  0.  0.  0. -1.  1.]
 [ 0. -1.  1.  0.  0.  0.]
 [-0. -0. -0. -1. -0. -0.]] 

xB = [[ 26.]
 [ 30.]
 [-11.]
 [-26.]
 [ -4.]
 [-32.]] 

x = [0, array([26.]), 0, 0, array([30.]), array([-11.]), array([-26.]), array([-4.]), 0, array([-32.]), 0, 0] 

cTx = [45.] 

Esta NÃO é uma solução básica viável

---------------------------------------------------------------------------


x 661
IB = 2 5 6 7 8 11
B = [[ 0  0  1 -1  0  0]
 [ 1  0  0  0 -1  0]
 [ 1  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  1  0  0  0 -1]
 [ 0  1  1  0  0  0]] 

A matriz B não é uma base
A linha LD é:
[[0 1 1 0 0 0]]

---------------------------------------------------------------------------


x 662
IB = 2 5 6 7 8 12
B = [[ 0  0  1 -1  0  0]
 [ 1  0  0  0 -1  0]
 [ 1  0  0 


---------------------------------------------------------------------------


x 718
IB = 3 4 5 6 7 11
B = [[ 0  0  0  1 -1  0]
 [ 0  0  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 1  1  0  0  0  0]
 [ 0  1  1  0  0 -1]
 [ 0  0  1  1  0  0]] 

A matriz B não é uma base
A linha LD é:
[[0 0 1 1 0 0]]

---------------------------------------------------------------------------


x 719
IB = 3 4 5 6 7 12
B = [[ 0  0  0  1 -1  0]
 [ 0  0  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 1  1  0  0  0  0]
 [ 0  1  1  0  0  0]
 [ 0  0  1  1  0 -1]] 

A matriz B não é uma base
A linha LD é:
[[ 0  1  1  0  0  0]
 [ 0  0  1  1  0 -1]]

---------------------------------------------------------------------------


x 720
IB = 3 4 5 6 8 9
B = [[ 0  0  0  1  0  0]
 [ 0  0  0  0 -1  0]
 [ 1  0  0  0  0 -1]
 [ 1  1  0  0  0  0]
 [ 0  1  1  0  0  0]
 [ 0  0  1  1  0  0]] 

B-1 = [[-1.  0.  0.  1. -1.  1.]
 [ 1.  0.  0.  0.  1. -1.]
 [-1.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.]
 [-0. -1. -0. -0. -0. -0.]
 [-1.  0. -1.

 [ 0  0  0  0  0 -1]] 

A matriz B não é uma base
A linha LD é:
[[ 0  1  0  0 -1  0]]

---------------------------------------------------------------------------


x 779
IB = 3 4 7 10 11 12
B = [[ 0  0 -1  0  0  0]
 [ 0  0  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 1  1  0 -1  0  0]
 [ 0  1  0  0 -1  0]
 [ 0  0  0  0  0 -1]] 

A matriz B não é uma base
A linha LD é:
[[ 0  1  0  0 -1  0]]

---------------------------------------------------------------------------


x 780
IB = 3 4 8 9 10 11
B = [[ 0  0  0  0  0  0]
 [ 0  0 -1  0  0  0]
 [ 1  0  0 -1  0  0]
 [ 1  1  0  0 -1  0]
 [ 0  1  0  0  0 -1]
 [ 0  0  0  0  0  0]] 

A matriz B não é uma base
A linha LD é:
[[ 0  1  0  0  0 -1]
 [ 0  0  0  0  0  0]]

---------------------------------------------------------------------------


x 781
IB = 3 4 8 9 10 12
B = [[ 0  0  0  0  0  0]
 [ 0  0 -1  0  0  0]
 [ 1  0  0 -1  0  0]
 [ 1  1  0  0 -1  0]
 [ 0  1  0  0  0  0]
 [ 0  0  0  0  0 -1]] 

A matriz B não é uma base
A linha LD é:
[[0 1 0 0 0 0]]



A linha LD é:
[[ 1  0 -1  0  0  0]
 [ 1  0  0 -1  0  0]]

---------------------------------------------------------------------------


x 840
IB = 3 8 9 10 11 12
B = [[ 0  0  0  0  0  0]
 [ 0 -1  0  0  0  0]
 [ 1  0 -1  0  0  0]
 [ 1  0  0 -1  0  0]
 [ 0  0  0  0 -1  0]
 [ 0  0  0  0  0 -1]] 

A matriz B não é uma base
A linha LD é:
[[ 1  0 -1  0  0  0]]

---------------------------------------------------------------------------


x 841
IB = 4 5 6 7 8 9
B = [[ 0  0  1 -1  0  0]
 [ 0  0  0  0 -1  0]
 [ 0  0  0  0  0 -1]
 [ 1  0  0  0  0  0]
 [ 1  1  0  0  0  0]
 [ 0  1  1  0  0  0]] 

B-1 = [[ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  1.  0.]
 [ 0.  0.  0.  1. -1.  1.]
 [-1.  0.  0.  1. -1.  1.]
 [-0. -1. -0. -0. -0. -0.]
 [-0. -0. -1. -0. -0. -0.]] 

xB = [[ 32.]
 [ -2.]
 [ 21.]
 [  6.]
 [-30.]
 [-26.]] 

x = [0, 0, 0, array([32.]), array([-2.]), array([21.]), array([6.]), array([-30.]), array([-26.]), 0, 0, 0] 

cTx = [51.] 

Esta NÃO é uma solução básica viável

-------------------


x 903
IB = 5 6 7 9 10 11
B = [[ 0  1 -1  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 -1  0  0]
 [ 0  0  0  0 -1  0]
 [ 1  0  0  0  0 -1]
 [ 1  1  0  0  0  0]] 

A matriz B não é uma base
A linha LD é:
[[1 1 0 0 0 0]]

---------------------------------------------------------------------------


x 904
IB = 5 6 7 9 10 12
B = [[ 0  1 -1  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 -1  0  0]
 [ 0  0  0  0 -1  0]
 [ 1  0  0  0  0  0]
 [ 1  1  0  0  0 -1]] 

A matriz B não é uma base
A linha LD é:
[[ 1  1  0  0  0 -1]]

---------------------------------------------------------------------------


x 905
IB = 5 6 7 9 11 12
B = [[ 0  1 -1  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 -1  0  0]
 [ 0  0  0  0  0  0]
 [ 1  0  0  0 -1  0]
 [ 1  1  0  0  0 -1]] 

A matriz B não é uma base
A linha LD é:
[[ 0  0  0 -1  0  0]
 [ 0  0  0  0  0  0]
 [ 1  0  0  0 -1  0]
 [ 1  1  0  0  0 -1]]

---------------------------------------------------------------------------


x 906
IB = 5 6 7 10 11 12
B = [[ 0  1 -1  0  

In [9]:
## Formatando os valores do todas_solucoes para sair bonitinho na tabela

for x in range(1, len(todas_solucoes)):
    try:
        todas_solucoes[x][2] = todas_solucoes[x][2][0]
    except:
        pass

for x in range(1, len(todas_solucoes)):
    for y in range(0, len(todas_solucoes)):
        try:
            todas_solucoes[x][3][y] = todas_solucoes[x][3][y][0]
        except:
            pass

todas_solucoes

array([[[0, 0, 0, 0, 0, 0], 0, 0, 0],
       [[1, 2, 3, 4, 5, 6], 1, [], []],
       [[1, 2, 3, 4, 5, 7], 2, 81.0,
        [25.0, 5.0, 21.0, 11.0, 19.0, 0, 10.0, 0, 0, 0, 0, 0]],
       ...,
       [[6, 7, 9, 10, 11, 12], 922, [], []],
       [[6, 8, 9, 10, 11, 12], 923, 15.0,
        [0, 0, 0, 0, 0, 15.0, 0, -30.0, -26.0, -32.0, -30.0, -4.0]],
       [[7, 8, 9, 10, 11, 12], 924, 0.0,
        [0, 0, 0, 0, 0, 0, -15.0, -30.0, -26.0, -32.0, -30.0, -19.0]]],
      dtype=object)

In [10]:
print("Todas as soluções:")

todas_solucoes = pd.DataFrame(todas_solucoes[1:,:], columns=['Conjunto de índices base', 'Id da solução', 'cTx', 'Solução básica associada à base'])
todas_solucoes.sort_values(by=['Id da solução'])

todas_solucoes

Todas as soluções:


Conjunto de índices base Id da solução   cTx  \
0         [1, 2, 3, 4, 5, 6]             1    []   
1         [1, 2, 3, 4, 5, 7]             2  81.0   
2         [1, 2, 3, 4, 5, 8]             3  71.0   
3         [1, 2, 3, 4, 5, 9]             4  81.0   
4        [1, 2, 3, 4, 5, 10]             5  71.0   
..                       ...           ...   ...   
919     [6, 7, 8, 9, 11, 12]           920    []   
920    [6, 7, 8, 10, 11, 12]           921    []   
921    [6, 7, 9, 10, 11, 12]           922    []   
922    [6, 8, 9, 10, 11, 12]           923  15.0   
923    [7, 8, 9, 10, 11, 12]           924   0.0   

                       Solução básica associada à base  
0                                                   []  
1    [25.0, 5.0, 21.0, 11.0, 19.0, 0, 10.0, 0, 0, 0...  
2    [15.0, 5.0, 21.0, 11.0, 19.0, 0, 0, -10.0, 0, ...  
3    [15.0, 15.0, 21.0, 11.0, 19.0, 0, 0, 0, 10.0, ...  
4    [15.0, 15.0, 11.0, 11.0, 19.0, 0, 0, 0, 0, -10...  
..                                                 ...  
919                                                 []  
920                                                 []  
921                                                 []  
922  [0, 0, 0, 0, 0, 15.0, 0, -30.0, -26.0, -32.0, ...  
923  [0, 0, 0, 0, 0, 0, -15.0, -30.0, -26.0, -32.0,...  

[924 rows x 4 columns]

In [11]:
qtd_solucoes_basicas = list(map(lambda z, sb=0: sb if z == [] else sb+1, todas_solucoes.loc[:, 'cTx'])).count(1)

print("\nQuantidade de soluções básicas: ", qtd_solucoes_basicas)


Quantidade de soluções básicas:  320


<ipython-input-11-243826ed9650>:1: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  qtd_solucoes_basicas = list(map(lambda z, sb=0: sb if z == [] else sb+1, todas_solucoes.loc[:, 'cTx'])).count(1)


In [12]:
## Formatando os valores do solucoes_viaveis para sair bonitinho na tabela

for x in range(1, len(solucoes_viaveis)):
    try:
        solucoes_viaveis[x][2] = solucoes_viaveis[x][2][0]
    except:
        pass

for x in range(1, len(solucoes_viaveis)):
    for y in range(0, len(solucoes_viaveis)):
        try:
            solucoes_viaveis[x][3][y] = solucoes_viaveis[x][3][y][0]
        except:
            pass

solucoes_viaveis

array([[[0, 0, 0, 0, 0, 0], 0, 0, 0],
       [[1, 2, 3, 4, 5, 7], 2, 81.0,
        [25.0, 5.0, 21.0, 11.0, 19.0, 0, 10.0, 0, 0, 0, 0, 0]],
       [[1, 2, 3, 4, 5, 9], 4, 81.0,
        [15.0, 15.0, 21.0, 11.0, 19.0, 0, 0, 0, 10.0, 0, 0, 0]],
       [[1, 2, 3, 4, 5, 11], 6, 81.0,
        [15.0, 15.0, 11.0, 21.0, 19.0, 0, 0, 0, 0, 0, 10.0, 0]],
       [[1, 2, 3, 4, 6, 7], 8, 81.0,
        [6.0, 24.0, 2.0, 30.0, 0, 19.0, 10.0, 0, 0, 0, 0, 0]],
       [[1, 2, 3, 5, 9, 12], 46, 92.0,
        [15.0, 15.0, 32.0, 0, 30.0, 0, 0, 0, 21.0, 0, 0, 11.0]],
       [[1, 2, 4, 5, 6, 11], 89, 81.0,
        [4.0, 26.0, 0, 32.0, 8.0, 11.0, 0, 0, 0, 0, 10.0, 0]],
       [[1, 2, 4, 5, 8, 11], 98, 92.0,
        [15.0, 26.0, 0, 32.0, 19.0, 0, 0, 11.0, 0, 0, 21.0, 0]],
       [[1, 2, 4, 6, 7, 11], 109, 81.0,
        [4.0, 26.0, 0, 32.0, 0, 19.0, 8.0, 0, 0, 0, 2.0, 0]],
       [[1, 3, 4, 5, 7, 10], 219, 86.0,
        [30.0, 0, 26.0, 11.0, 19.0, 0, 15.0, 0, 0, 5.0, 0, 0]],
       [[1, 3, 4, 5, 7, 12], 221, 86.0,


In [13]:
print("Soluções viáveis:")

solucoes_viaveis = pd.DataFrame(solucoes_viaveis[1:,:], columns=['Conjunto de índices base', 'Id da solução', 'cTx', 'Solução básica associada à base'])
solucoes_viaveis.sort_values(by=['Id da solução'])

solucoes_viaveis

Soluções viáveis:


Conjunto de índices base Id da solução    cTx  \
0        [1, 2, 3, 4, 5, 7]             2   81.0   
1        [1, 2, 3, 4, 5, 9]             4   81.0   
2       [1, 2, 3, 4, 5, 11]             6   81.0   
3        [1, 2, 3, 4, 6, 7]             8   81.0   
4       [1, 2, 3, 5, 9, 12]            46   92.0   
5       [1, 2, 4, 5, 6, 11]            89   81.0   
6       [1, 2, 4, 5, 8, 11]            98   92.0   
7       [1, 2, 4, 6, 7, 11]           109   81.0   
8       [1, 3, 4, 5, 7, 10]           219   86.0   
9       [1, 3, 4, 5, 7, 12]           221   86.0   
10      [1, 3, 4, 6, 7, 10]           234  105.0   
11      [1, 3, 5, 7, 9, 12]           288   92.0   
12       [2, 3, 4, 5, 6, 9]           465   81.0   
13       [2, 3, 4, 6, 7, 9]           485   81.0   
14      [2, 3, 5, 6, 9, 12]           530  107.0   
15      [2, 4, 5, 6, 9, 11]           599   81.0   
16      [2, 4, 6, 7, 9, 11]           629   81.0   

                      Solução básica associada à base  
0   [25.0, 5.0, 21.0, 11.0, 19.0, 0, 10.0, 0, 0, 0...  
1   [15.0, 15.0, 21.0, 11.0, 19.0, 0, 0, 0, 10.0, ...  
2   [15.0, 15.0, 11.0, 21.0, 19.0, 0, 0, 0, 0, 0, ...  
3   [6.0, 24.0, 2.0, 30.0, 0, 19.0, 10.0, 0, 0, 0,...  
4   [15.0, 15.0, 32.0, 0, 30.0, 0, 0, 0, 21.0, 0, ...  
5   [4.0, 26.0, 0, 32.0, 8.0, 11.0, 0, 0, 0, 0, 10...  
6   [15.0, 26.0, 0, 32.0, 19.0, 0, 0, 11.0, 0, 0, ...  
7   [4.0, 26.0, 0, 32.0, 0, 19.0, 8.0, 0, 0, 0, 2....  
8   [30.0, 0, 26.0, 11.0, 19.0, 0, 15.0, 0, 0, 5.0...  
9   [30.0, 0, 26.0, 6.0, 24.0, 0, 15.0, 0, 0, 0, 0...  
10  [30.0, 0, 26.0, 30.0, 0, 19.0, 34.0, 0, 0, 24....  
11  [30.0, 0, 32.0, 0, 30.0, 0, 15.0, 0, 6.0, 0, 0...  
12  [0, 30.0, 6.0, 26.0, 4.0, 15.0, 0, 0, 10.0, 0,...  
13  [0, 30.0, 2.0, 30.0, 0, 19.0, 4.0, 0, 6.0, 0, ...  
14  [0, 30.0, 32.0, 0, 30.0, 15.0, 0, 0, 36.0, 0, ...  
15  [0, 30.0, 0, 32.0, 4.0, 15.0, 0, 0, 4.0, 0, 6....  
16  [0, 30.0, 0, 32.0, 0, 19.0, 4.0, 0, 4.0, 0, 2....

In [14]:
qtd_solucoes_viaveis = len(solucoes_viaveis)
print("\nQuantidade de soluções viáveis: ", qtd_solucoes_viaveis)


Quantidade de soluções viáveis:  17


In [15]:
## Digite 1 se você deseja maximizar ou 2 se você deseja minimizar
entrada = 2 # Queremos reduzir o número de motoristas

if(entrada == 1):
    id_solucao_otima = solucoes_viaveis['cTx'].astype(float).argmax()
elif(entrada == 2):
    id_solucao_otima = solucoes_viaveis['cTx'].astype(float).argmin()
    
solucao_otima = solucoes_viaveis['cTx'][id_solucao_otima]
geram_solucoes_otimas =  solucoes_viaveis['cTx'][id_solucao_otima]
print('Solução Ótima:', solucao_otima)


Solução Ótima: 81.0


In [16]:
print('\nSoluções que geram a solução ótima:\n')

geram_solucoes_otimas = solucoes_viaveis.loc[solucoes_viaveis['cTx'] == solucao_otima, :]
geram_solucoes_otimas


Soluções que geram a solução ótima:



Conjunto de índices base Id da solução   cTx  \
0        [1, 2, 3, 4, 5, 7]             2  81.0   
1        [1, 2, 3, 4, 5, 9]             4  81.0   
2       [1, 2, 3, 4, 5, 11]             6  81.0   
3        [1, 2, 3, 4, 6, 7]             8  81.0   
5       [1, 2, 4, 5, 6, 11]            89  81.0   
7       [1, 2, 4, 6, 7, 11]           109  81.0   
12       [2, 3, 4, 5, 6, 9]           465  81.0   
13       [2, 3, 4, 6, 7, 9]           485  81.0   
15      [2, 4, 5, 6, 9, 11]           599  81.0   
16      [2, 4, 6, 7, 9, 11]           629  81.0   

                      Solução básica associada à base  
0   [25.0, 5.0, 21.0, 11.0, 19.0, 0, 10.0, 0, 0, 0...  
1   [15.0, 15.0, 21.0, 11.0, 19.0, 0, 0, 0, 10.0, ...  
2   [15.0, 15.0, 11.0, 21.0, 19.0, 0, 0, 0, 0, 0, ...  
3   [6.0, 24.0, 2.0, 30.0, 0, 19.0, 10.0, 0, 0, 0,...  
5   [4.0, 26.0, 0, 32.0, 8.0, 11.0, 0, 0, 0, 0, 10...  
7   [4.0, 26.0, 0, 32.0, 0, 19.0, 8.0, 0, 0, 0, 2....  
12  [0, 30.0, 6.0, 26.0, 4.0, 15.0, 0, 0, 10.0, 0,...  
13  [0, 30.0, 2.0, 30.0, 0, 19.0, 4.0, 0, 6.0, 0, ...  
15  [0, 30.0, 0, 32.0, 4.0, 15.0, 0, 0, 4.0, 0, 6....  
16  [0, 30.0, 0, 32.0, 0, 19.0, 4.0, 0, 4.0, 0, 2....

In [17]:
print("\nQuantidade de soluções viáveis: ", qtd_solucoes_viaveis)
print("\nQuantidade de soluções básicas: ", qtd_solucoes_basicas)
print('\nO número máximo de soluções básicas:', combinacoes)
print('\nSolução Ótima:', solucao_otima)


Quantidade de soluções viáveis:  17

Quantidade de soluções básicas:  320

O número máximo de soluções básicas: 924.0

Solução Ótima: 81.0
